services:
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./data/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data

  gatekeeper:
    image: keychainmdip/gatekeeper:release
    environment:
      - KC_GATEKEEPER_PORT=4224
      - KC_GATEKEEPER_DB=redis
      - KC_GATEKEEPER_DID_PREFIX=did:mdip
      - KC_GATEKEEPER_GC_INTERVAL=240
      - KC_GATEKEEPER_STATUS_INTERVAL=1
      - KC_REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/gatekeeper/data
    user: "${KC_UID}:${KC_GID}"
    ports:
      - 4224:4224
    depends_on:
      - redis

  keymaster:
    image: keychainmdip/keymaster:release
    environment:
      - KC_KEYMASTER_PORT=4226
      - KC_GATEKEEPER_URL=http://gatekeeper:4224
      - KC_KEYMASTER_DB=redis
      - KC_ENCRYPTED_PASSPHRASE=${KC_ENCRYPTED_PASSPHRASE}
      - KC_WALLET_CACHE=true
      - KC_REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/keymaster/data
    user: "${KC_UID}:${KC_GID}"
    ports:
      - 4226:4226
    depends_on:
      - gatekeeper

  hypr-mediator:
    image: keychainmdip/hyperswarm-mediator:release
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper:4224
      - KC_NODE_NAME=${KC_NODE_NAME}
      - KC_MDIP_PROTOCOL=/MDIP/v1.0-public
      - KC_HYPR_EXPORT_INTERVAL=2
    volumes:
      - ./data:/app/hyperswarm/data
    user: "${KC_UID}:${KC_GID}"
    depends_on:
      - gatekeeper

  cli:
    image: keychainmdip/cli:release
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper:4224
      - KC_KEYMASTER_URL=http://keymaster:4226
    depends_on:
      - gatekeeper
      - keymaster

  tftc-node:
    image: keychainmdip/feathercoin:v0.19.1
    volumes:
      - ./data/tftc:/root/.feathercoin

  tftc-mediator:
    image: keychainmdip/sat-mediator:release
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper:4224
      - KC_KEYMASTER_URL=http://keymaster:4226
      - KC_NODE_ID=${KC_NODE_ID}
      - KC_SAT_USER=${KC_TFTC_USER}
      - KC_SAT_PASS=${KC_TFTC_PASS}
      - KC_SAT_CHAIN=TFTC
      - KC_SAT_NETWORK=testnet
      - KC_SAT_START_BLOCK=0
      - KC_SAT_HOST=tftc-node
      - KC_SAT_PORT=19337
      - KC_SAT_WALLET=mdip
      - KC_SAT_IMPORT_INTERVAL=1
      - KC_SAT_EXPORT_INTERVAL=0
      - KC_SAT_FEE_MIN=0
      - KC_SAT_FEE_MAX=0
      - KC_SAT_FEE_INC=0
      - KC_SAT_REIMPORT=true
      - KC_SAT_DB=redis
      - KC_REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/satoshi/data
    user: "${KC_UID}:${KC_GID}"
    depends_on:
      - tftc-node
      - gatekeeper
      - keymaster

  tbtc-node:
    image: keychainmdip/bitcoin-core:v28.0-multiarch
    volumes:
      - ./data/tbtc:/root/.bitcoin

  tbtc-mediator:
    image: keychainmdip/sat-mediator:release
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper:4224
      - KC_KEYMASTER_URL=http://keymaster:4226
      - KC_MONGODB_URL=mongodb://mongodb:27017
      - KC_NODE_ID=${KC_NODE_ID}
      - KC_SAT_USER=${KC_TBTC_USER}
      - KC_SAT_PASS=${KC_TBTC_PASS}
      - KC_SAT_CHAIN=TBTC
      - KC_SAT_NETWORK=testnet
      - KC_SAT_HOST=tbtc-node
      - KC_SAT_PORT=48332
      - KC_SAT_START_BLOCK=38000
      - KC_SAT_WALLET=mdip
      - KC_SAT_IMPORT_INTERVAL=1
      - KC_SAT_EXPORT_INTERVAL=0
      - KC_SAT_FEE_MIN=0
      - KC_SAT_FEE_MAX=0
      - KC_SAT_FEE_INC=0
      - KC_SAT_REIMPORT=true
      - KC_SAT_DB=redis
      - KC_REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/satoshi/data
    user: "${KC_UID}:${KC_GID}"
    depends_on:
      - tbtc-node
      - gatekeeper
      - keymaster

  ipfs-mediator:
    image: keychainmdip/ipfs-mediator:release
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper:4224
      - KC_IPFS_INTERVAL=60
      - KC_IPFS_BATCH_SIZE=100
      - KC_IPFS_CONCURRENCY=10
    volumes:
      - ./data:/app/ipfs/data
    user: "${KC_UID}:${KC_GID}"
    depends_on:
      - gatekeeper

