services:
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./data/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data

  gatekeeper:
    image: keychainmdip/gatekeeper:release
    environment:
      - KC_GATEKEEPER_PORT=4224
      - KC_GATEKEEPER_DB=redis
      - KC_GATEKEEPER_DID_PREFIX=did:mdip
      - KC_GATEKEEPER_GC_INTERVAL=240
      - KC_GATEKEEPER_STATUS_INTERVAL=1
      - KC_REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/gatekeeper/data
    user: "${KC_UID}:${KC_GID}"
    ports:
      - 4224:4224
    depends_on:
      - redis

  keymaster:
    image: keychainmdip/keymaster:release
    environment:
      - KC_KEYMASTER_PORT=4226
      - KC_GATEKEEPER_URL=http://gatekeeper:4224
      - KC_KEYMASTER_DB=redis
      - KC_ENCRYPTED_PASSPHRASE=${KC_ENCRYPTED_PASSPHRASE}
      - KC_WALLET_CACHE=true
      - KC_REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/keymaster/data
    user: "${KC_UID}:${KC_GID}"
    ports:
      - 4226:4226
    depends_on:
      - gatekeeper

  hypr-mediator:
    image: keychainmdip/hyperswarm-mediator:release
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper:4224
      - KC_NODE_NAME=${KC_NODE_NAME}
      - KC_MDIP_PROTOCOL=/MDIP/v1.0-public
      - KC_HYPR_EXPORT_INTERVAL=2
    volumes:
      - ./data:/app/hyperswarm/data
    user: "${KC_UID}:${KC_GID}"
    depends_on:
      - gatekeeper

  cli:
    image: keychainmdip/cli:release
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper:4224
      - KC_KEYMASTER_URL=http://keymaster:4226
    depends_on:
      - gatekeeper
      - keymaster
