version: "3"
services:

  gatekeeper:
    image: ghcr.io/keychainmdip/gatekeeper:release
    volumes:
      - ./data:/app/data
    ports:
      - "4224:4224"

  hyperswarm:
    image: ghcr.io/keychainmdip/hyperswarm-mediator:release
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper
      - KC_GATEKEEPER_PORT=4224
    volumes:
      - ./data:/app/data
    depends_on:
      - gatekeeper
