services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./data/mongodb:/data/db

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./data/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data

  gatekeeper:
    image: keychainmdip/gatekeeper:release
    environment:
      - KC_GATEKEEPER_PORT=4224
      - KC_GATEKEEPER_DB=${KC_GATEKEEPER_DB}
      - KC_GATEKEEPER_DID_PREFIX=${KC_GATEKEEPER_DID_PREFIX}
      - KC_GATEKEEPER_REGISTRIES=${KC_GATEKEEPER_REGISTRIES}
      - KC_GATEKEEPER_GC_INTERVAL=${KC_GATEKEEPER_GC_INTERVAL}
      - KC_GATEKEEPER_STATUS_INTERVAL=${KC_GATEKEEPER_STATUS_INTERVAL}
      - KC_MONGODB_URL=mongodb://mongodb:27017
      - KC_REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/gatekeeper/data
    user: "${KC_UID}:${KC_GID}"
    ports:
      - 4224:4224
    depends_on:
      - mongodb
      - redis

  keymaster:
    image: keychainmdip/keymaster:release
    environment:
      - KC_KEYMASTER_PORT=4226
      - KC_GATEKEEPER_URL=http://gatekeeper:4224
      - KC_KEYMASTER_DB=${KC_KEYMASTER_DB}
      - KC_ENCRYPTED_PASSPHRASE=${KC_ENCRYPTED_PASSPHRASE}
      - KC_WALLET_CACHE=${KC_WALLET_CACHE}
      - KC_MONGODB_URL=mongodb://mongodb:27017
      - KC_REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/keymaster/data
    user: "${KC_UID}:${KC_GID}"
    ports:
      - 4226:4226
    depends_on:
      - gatekeeper

  hypr-mediator:
    image: keychainmdip/hyperswarm-mediator:release
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper:4224
      - KC_NODE_NAME=${KC_NODE_NAME}
      - KC_MDIP_PROTOCOL=${KC_MDIP_PROTOCOL}
      - KC_HYPR_EXPORT_INTERVAL=${KC_HYPR_EXPORT_INTERVAL}
    volumes:
      - ./data:/app/hyperswarm/data
    user: "${KC_UID}:${KC_GID}"
    depends_on:
      - gatekeeper

  ipfs-mediator:
    image: keychainmdip/ipfs-mediator:release
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper:4224
      - KC_IPFS_INTERVAL=${KC_IPFS_INTERVAL}
      - KC_IPFS_BATCH_SIZE=${KC_IPFS_BATCH_SIZE}
      - KC_IPFS_CONCURRENCY=${KC_IPFS_CONCURRENCY}
    volumes:
      - ./data:/app/ipfs/data
    user: "${KC_UID}:${KC_GID}"
    depends_on:
      - gatekeeper

  cli:
    image: keychainmdip/cli:release
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper:4224
      - KC_KEYMASTER_URL=http://keymaster:4226
    depends_on:
      - gatekeeper
      - keymaster
